---
# ------------------------------------------------------------------------------
# MOUNTS
# ------------------------------------------------------------------------------
mount_devices:
  - name: /var/lib/docker
    mode: '0711'
    createpath: true
    createfs: true
    src: /dev/sdb
    fstype: xfs
    state: mounted

  - name: /opt/local-path-provisioner
    createpath: true
    createfs: true
    src: /dev/sdc
    fstype: xfs
    state: mounted

# ------------------------------------------------------------------------------
# RKE
# ------------------------------------------------------------------------------
rke_secrets: "{{ lookup('hashi_vault', 'secret=secret/data/dev/rke') }}"

# rke binary version
rke_version: 1.0.4
rke_checksum: sha256:8219a09dbf21b2712ae21a2a43c86e941eeeaccd791552e806026c092f5a94cb

rke_node_user: centos
rke_node_user_ssh_public_key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDFAPWyoqBkZIlGVjbMFJkNfMMWiTAxMvR2oThsGqHdjkSZypC2JogKlTFe+jBz9Gp7tEmiuU5r8yfANyvtGTVEjfrckXtqHc9HW5rjmdDyLoBVd1mlppsWnhO12xo4yt+61IeXrGhPzqflui+XyhmFvqdTk/8Kx/eizyHuHBXbovzmJab/ApQFv6gs4buTaepqWHSfetH4eLOHyvra/5b0VZyxoSdzuhcovsCARkOqRMVA2p4B+SYV4rfUK/Z2TVHuhN8Yx6JY83P2UcuGdha6HkfcIroPAQRvsqoZnUWo+gnZ2Hjzhs3lD1BuGvKQrmAJONvBa3JkOkEUI87aHLWv noe.gonzalez@dev.noe.local

rke_cluster_name: dev-rancher-01

rke_node_user_ssh_private_key: "{{ global_secrets['data']['ssh_private_key'] }}"

rke_nodes:
  - address: dev-rancher-01
    user: centos
    role: [controlplane,etcd,worker]

rke_ingress_default_crt: "{{ env_wildcard_ssl_cert + env_wildcard_ssl_ca }}"
rke_ingress_default_key: "{{ env_wildcard_ssl_key }}"
