---
vault_helm_chart:
  name: vault
  version: 0.10.0
  release: vault
  namespace: vault
  source:
    type: git
    location: https://github.com/banzaicloud/bank-vaults.git
    reference: chart/vault/0.10.0
    path: charts/vault
  state: present
  values:
    ingress:
      enabled: true
      hosts:
        - vault.dev.noeg.wtf
      annotations:
        kubernetes.io/ingress.class: nginx
        ingress.kubernetes.io/ssl-redirect: 'true'
        certmanager.k8s.io/acme-challenge-type: dns01
        certmanager.k8s.io/acme-dns01-provider: cloudflare
        certmanager.k8s.io/cluster-issuer: letsencrypt-prod
        nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
      tls:
      - secretName: vault-tls-prod
        hosts:
        - vault.dev.noeg.wtf

    persistence:
      ## Enable persistence using Persistent Volume Claims
      ## ref: http://kubernetes.io/docs/user-guide/persistent-volumes/
      enabled: true

    vault:
      externalConfig:
        # Allows creating policies in Vault which can be used later on in roles
        # for the Kubernetes based authentication.
        # See https://www.vaultproject.io/docs/concepts/policies.html for more information.
        policies:
          - name: allow_secrets
            rules: path "secret/*" {
                    capabilities = ["create", "read", "update", "delete", "list"]
                  }
          - name: allow_admin
            rules: path "*" {
                    capabilities = ["create", "read", "update", "delete", "list", "sudo"]
                  }
        auth:
          - type: kubernetes
            # Allows creating roles in Vault which can be used later on for the Kubernetes based
            # authentication.
            # See https://www.vaultproject.io/docs/auth/kubernetes.html#creating-a-role for
            # more information.
            roles:
              # Allow every pod in the default namespace to use the secret kv store
              - name: jenkins
                bound_service_account_names: jenkins
                bound_service_account_namespaces: jenkins
                policies: allow_secrets
                ttl: 1h
        secrets:
          - path: secret
            type: kv
            description: General secrets.
            options:
              version: 2
      config:
        # See https://www.vaultproject.io/docs/configuration/storage/ for storage backends
        storage:
          file:
            path: "/vault/file"

      logLevel: debug

    unsealer:
      args: [
          "--mode",
          "k8s",
          "--k8s-secret-namespace",
          "vault",
          "--k8s-secret-name",
          "bank-vaults"
      ]
