---
grafana_helm_chart:
  name: grafana
  version: 4.3.0
  release: grafana
  namespace: grafana
  source:
    type: repo
    location: https://kubernetes-charts.storage.googleapis.com
  state: present
  values:
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: nginx
        ingress.kubernetes.io/ssl-redirect: 'true'
        certmanager.k8s.io/acme-challenge-type: dns01
        certmanager.k8s.io/acme-dns01-provider: cloudflare
        certmanager.k8s.io/cluster-issuer: letsencrypt-prod
      hosts:
        - grafana.dev.noeg.wtf
      tls:
        - secretName: grafana-tls-prod
          hosts:
            - grafana.dev.noeg.wtf

    persistence:
      enabled: true

    adminUser: admin
    adminPassword: "{{ global_secrets['data']['password'] }}"
