- hosts: app_esxi
  tasks:

    - name: copy ssl cert
      copy:
        content: "{{ esxi_ssl_crt }}"
        dest: /etc/vmware/ssl/rui.crt
        backup: true
        mode: 0644
      register: l_ssl_cert

    - name: copy ssl key
      copy:
        content: "{{ esxi_ssl_key }}"
        dest: /etc/vmware/ssl/rui.key
        backup: true
        mode: 0644
      register: l_ssl_key  

    - name: restart management services if certificate or key changed
      command: "{{ item }}"
      loop:
        - /etc/init.d/hostd restart
        - /etc/init.d/vpxa restart
      when:
        - l_ssl_cert.changed or l_ssl_key.changed

    - name: Configure NTP servers for an ESXi Host
      vmware_host_ntp:
        hostname: "{{ inventory_hostname }}"
        username: "{{ ansible_user }}"
        password: "{{ ansible_password }}"
        esxi_hostname: "{{ inventory_hostname }}"
        ntp_servers: "{{ esxi_ntp_servers }}"
      delegate_to: localhost

    - name: Start ntpd setting for an ESXi Host with Service policy
      vmware_host_service_manager:
        hostname: "{{ inventory_hostname }}"
        username: "{{ ansible_user }}"
        password: "{{ ansible_password }}"
        esxi_hostname: "{{ inventory_hostname }}"
        service_name: ntpd
        service_policy: on
        state: present
      delegate_to: localhost
