- hosts: network_edge_os
  tasks:
    - name: collect all facts from the device
      edgeos_facts:
        gather_subset: all
      register: l_edge_os_facts

    - name: debug
      debug:
        msg: "{{ l_edge_os_facts }}"
