---
- hosts: product_rancher
  roles:
    - ansible-role-helm
    - ansible-role-cert-manager

- hosts: product_rancher
  roles:
    - ansible-role-rancher
    - ansible-role-local-path-provisioner

- hosts: product_rancher
  tasks:
    - name: patch ingress
      k8s:
        state: present
        definition: |
          apiVersion: extensions/v1beta1
          kind: Ingress
          metadata:
            name: rancher
            namespace: cattle-system
            annotations:
              cert-manager.io/cluster-issuer: letsencrypt-prod
          spec:
            tls:
            - hosts:
              - {{ rancher_helm_chart['values']['hostname'] }}
              secretName: rancher-tls-prod
