---
- hosts: product_certmanager
  vars:
    cert_manager_helm_release_name: cert-manager
    cert_manager_version: v0.9.1
    cert_manager_required_manifests:
      - https://raw.githubusercontent.com/jetstack/cert-manager/{{ cert_manager_version }}/deploy/manifests/01-namespace.yaml
      - https://raw.githubusercontent.com/jetstack/cert-manager/{{ cert_manager_version }}/deploy/manifests/00-crds.yaml
    rancher_helm_release_name: rancher

  tasks:
    - name: remove rancher helm release
      command: "helm delete {{ rancher_helm_release_name }} --purge"

    - name: remove cert-manager helm release
      command: "helm delete {{ cert_manager_helm_release_name }} --purge"

    - name: delete cert-manger CRDs & namespace
      command: "kubectl delete -f {{ item }}"
      loop: "{{ cert_manager_required_manifests }}"
